package urb.projects.facturas.domain;

public enum InvoiceErrors {
    ERROR_AL_CONSULTAR_EN_SITIO_WEB,
    SE_OBTUBOO_MAS_DE_UN_RESULTADO,
    NO_COINCIDE_CANTIDAD_CON_PAGINA_WEB,
    ERROR_AL_PROCESAR_XML,
    NO_COINCIDE_CANTIDAD_CON_XML,
    ERROR_AL_DESCARGAR_PDF,
    ERROR_AL_DESCARGAR_XML,
    NO_SE_ENCONTRO_RESULTADO,
    CANTIDADES_NO_COINCIDEN,
    NO_SE_ENCONTRO_RESULTADO_COM_FECHA
}
